### PR TITLE
sort by author's name

### LINKED ISSUE #6: Sort by author's name?
For easy navigation.

### PR DESCRIPTION
**Pull request by bilgin1500**
Closes #6
Also my first PR
Also great resource, thanks!

### CODE REVIEW

**Comment by hugmanrique** [comment]
A better way to do this automatically would be to create a source JSON file and a Node.js/Python/whatever script that ordered the entries alphabetically.

This would also give others the possibility of retrieving the raw JSON data for custom UIs, projects...

**Comment by bilgin1500** [comment]
I agree that such approach would bring some possibilities, especially thinking of  RSS readers and such, at some point the project will need a flexible solution for storing its data. But for now, maybe we should keep it simple.

**Comment by jkup** [comment]
Wow thanks so much for doing this!

**Comment by jkup** [comment]
@hugmanrique that would be an awesome approach! Maybe open an issue so we can talk about what would be the best direction for the project?

**Pull request merged**
